### ISSUE TITLE
support "Edit this page" in docs

### ISSUE THREAD

**Issue by juzhiyuan** [apache/apisix-website#218]
Hi, I noticed that on our website, we don't have an `Edit this page` link, it's useful for visitors to submit feedbacks like a typo fix, etc.

We could check https://v2.docusaurus.io/docs/ first to see if it supports this feature.

**Comment by akshitadixit** [comment]
Hello may I work on this?

**Comment by juzhiyuan** [comment]
Of course!

**Comment by akshitadixit** [comment]
@juzhiyuan please clarify a few things since I'm relatively new with things here:
1. Do you require a button on the homepage only?
2. Do you require a link in someplace like the footer?
3. Do you require the edit option on every docs page?

Also it would be really great of you if you could guide me about the exact file I will need to make the changes to, pardon me for such a basic question and I understand that you might have other engagements. Kindly overlook if this sounds too naive.

**Comment by juzhiyuan** [comment]
Hello! @qier222 will guide you when he's free :)

**Comment by akshitadixit** [comment]
Sure

**Comment by qier222** [comment]
I prefer to add "Edit this page" on every docs page, just like docusaurus.

**Comment by juzhiyuan** [comment]
ok, @akshitadixit, could you please have a Google search about `Edit this page in docusaurus` first?

**Comment by qier222** [comment]
https://v2.docusaurus.io/docs/next/api/plugins/@docusaurus/plugin-content-docs

**Comment by akshitadixit** [comment]
@qier222 @juzhiyuan I am extremely sorry about taking up your time, but this is currently advanced for a beginner like me. I'm afraid I cannot solve this issue.

**Comment by qier222** [comment]
> @qier222 @juzhiyuan I am extremely sorry about taking up your time, but this is currently advanced for a beginner like me. I'm afraid I cannot solve this issue.

It's ok

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/109787444-2f1fc480-7c49-11eb-90c5-c9909494fd75.png)

Does this mean if we add this URL on every doc file, then that page will have an `Edit this page` link?

**Comment by qier222** [comment]
check out this pr
https://github.com/apache/apisix-website/pull/235
